/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jivesoftware_idlelinux_LinuxIdle */

#ifndef _Included_com_jivesoftware_idlelinux_LinuxIdle
#define _Included_com_jivesoftware_idlelinux_LinuxIdle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jivesoftware_idlelinux_LinuxIdle
 * Method:    idleTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jivesoftware_idlelinux_LinuxIdle_idleTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
